from snakemake.utils import min_version

min_version("6.10.0")

# Configuration file containing all user-specified settings
configfile: "config/config.yml"

report: "report/workflow.rst"


include: "rules/qiime2_composite.smk"
include: "rules/mothur_composite.smk"
include: "rules/phyloseq_objects.smk"
include: "rules/plot_merged_taxa.smk"
include: "rules/rmd_report.smk"

rule all:
    input:
        "data/mothur_phyloseq_objects.rda",
        "data/qiime2_phyloseq_objects.rda",

        "figures/taxon_barplot.svg",
        "images/smkreport/screenshot.png",
        "report.html",
        "index.html",
        # "data/qiime2_composite.csv",
        # "data/qiime2_tidy_taxonomy.csv",
        # "data/qiime2_tidy_features.csv",
        # "data/qiime2_tidy_metadata.csv",
        # "data/qiime2_taxonomy.tsv",
        # "data/qiime2_features.tsv",
        # "data/qiime2_metadata.tsv",
        
        # "data/mothur_composite.csv",
        # "data/mothur_tidy_taxonomy.csv",
        # "data/mothur_tidy_otutable.csv",
        # "data/mothur_tidy_metadata.csv",
        # "data/mothur_taxonomy.tsv",
        # "data/mothur_otutable.tsv",
        # "data/mothur_metadata.tsv",


